kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  tagSpecification_1: "App=TestApp"
  tagSpecification_2: "pvcnamespace={{ .PVCNamespace }}"
  tagSpecification_3: "pvcname={{ .PVCName }}"
  tagSpecification_4: "pvname={{ .PVName }}"